// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "body/body_white_balance.proto" (package "tv.yunxi.protobuf.body", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message tv.yunxi.protobuf.body.WhiteBalanceManual
 */
export interface WhiteBalanceManual {
    /**
     * @generated from protobuf field: uint32 saturation = 1;
     */
    saturation: number;
    /**
     * @generated from protobuf field: uint32 chroma = 2;
     */
    chroma: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class WhiteBalanceManual$Type extends MessageType<WhiteBalanceManual> {
    constructor() {
        super("tv.yunxi.protobuf.body.WhiteBalanceManual", [
            { no: 1, name: "saturation", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "chroma", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<WhiteBalanceManual>): WhiteBalanceManual {
        const message = { saturation: 0, chroma: 0 };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<WhiteBalanceManual>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WhiteBalanceManual): WhiteBalanceManual {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 saturation */ 1:
                    message.saturation = reader.uint32();
                    break;
                case /* uint32 chroma */ 2:
                    message.chroma = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WhiteBalanceManual, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 saturation = 1; */
        if (message.saturation !== 0)
            writer.tag(1, WireType.Varint).uint32(message.saturation);
        /* uint32 chroma = 2; */
        if (message.chroma !== 0)
            writer.tag(2, WireType.Varint).uint32(message.chroma);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message tv.yunxi.protobuf.body.WhiteBalanceManual
 */
export const WhiteBalanceManual = new WhiteBalanceManual$Type();
