// source: command_body_struct.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.tv.yunxi.protobuf.CommandBody');
goog.provide('proto.tv.yunxi.protobuf.CommandBody.ValueCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.tv.yunxi.protobuf.body.ManualExposureParams');
goog.require('proto.tv.yunxi.protobuf.body.Range');
goog.require('proto.tv.yunxi.protobuf.body.Rect');
goog.require('proto.tv.yunxi.protobuf.body.Size');
goog.require('proto.tv.yunxi.protobuf.body.TransportFile');
goog.require('proto.tv.yunxi.protobuf.body.WhiteBalanceManual');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tv.yunxi.protobuf.CommandBody = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_);
};
goog.inherits(proto.tv.yunxi.protobuf.CommandBody, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tv.yunxi.protobuf.CommandBody.displayName = 'proto.tv.yunxi.protobuf.CommandBody';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.tv.yunxi.protobuf.CommandBody.oneofGroups_ = [[1,2,3,4,5,6,7,8]];

/**
 * @enum {number}
 */
proto.tv.yunxi.protobuf.CommandBody.ValueCase = {
  VALUE_NOT_SET: 0,
  INT_VAL: 1,
  STR_VAL: 2,
  EXPOSURE_PARAMS: 3,
  WHITE_BALANCE_MANUAL: 4,
  TRANSPORT_FILE: 5,
  SIZE: 6,
  RANGE: 7,
  RECT: 8
};

/**
 * @return {proto.tv.yunxi.protobuf.CommandBody.ValueCase}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getValueCase = function() {
  return /** @type {proto.tv.yunxi.protobuf.CommandBody.ValueCase} */(jspb.Message.computeOneofCase(this, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.toObject = function(opt_includeInstance) {
  return proto.tv.yunxi.protobuf.CommandBody.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tv.yunxi.protobuf.CommandBody} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tv.yunxi.protobuf.CommandBody.toObject = function(includeInstance, msg) {
  var f, obj = {
    intVal: jspb.Message.getFieldWithDefault(msg, 1, 0),
    strVal: jspb.Message.getFieldWithDefault(msg, 2, ""),
    exposureParams: (f = msg.getExposureParams()) && proto.tv.yunxi.protobuf.body.ManualExposureParams.toObject(includeInstance, f),
    whiteBalanceManual: (f = msg.getWhiteBalanceManual()) && proto.tv.yunxi.protobuf.body.WhiteBalanceManual.toObject(includeInstance, f),
    transportFile: (f = msg.getTransportFile()) && proto.tv.yunxi.protobuf.body.TransportFile.toObject(includeInstance, f),
    size: (f = msg.getSize()) && proto.tv.yunxi.protobuf.body.Size.toObject(includeInstance, f),
    range: (f = msg.getRange()) && proto.tv.yunxi.protobuf.body.Range.toObject(includeInstance, f),
    rect: (f = msg.getRect()) && proto.tv.yunxi.protobuf.body.Rect.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tv.yunxi.protobuf.CommandBody}
 */
proto.tv.yunxi.protobuf.CommandBody.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tv.yunxi.protobuf.CommandBody;
  return proto.tv.yunxi.protobuf.CommandBody.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tv.yunxi.protobuf.CommandBody} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tv.yunxi.protobuf.CommandBody}
 */
proto.tv.yunxi.protobuf.CommandBody.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setIntVal(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrVal(value);
      break;
    case 3:
      var value = new proto.tv.yunxi.protobuf.body.ManualExposureParams;
      reader.readMessage(value,proto.tv.yunxi.protobuf.body.ManualExposureParams.deserializeBinaryFromReader);
      msg.setExposureParams(value);
      break;
    case 4:
      var value = new proto.tv.yunxi.protobuf.body.WhiteBalanceManual;
      reader.readMessage(value,proto.tv.yunxi.protobuf.body.WhiteBalanceManual.deserializeBinaryFromReader);
      msg.setWhiteBalanceManual(value);
      break;
    case 5:
      var value = new proto.tv.yunxi.protobuf.body.TransportFile;
      reader.readMessage(value,proto.tv.yunxi.protobuf.body.TransportFile.deserializeBinaryFromReader);
      msg.setTransportFile(value);
      break;
    case 6:
      var value = new proto.tv.yunxi.protobuf.body.Size;
      reader.readMessage(value,proto.tv.yunxi.protobuf.body.Size.deserializeBinaryFromReader);
      msg.setSize(value);
      break;
    case 7:
      var value = new proto.tv.yunxi.protobuf.body.Range;
      reader.readMessage(value,proto.tv.yunxi.protobuf.body.Range.deserializeBinaryFromReader);
      msg.setRange(value);
      break;
    case 8:
      var value = new proto.tv.yunxi.protobuf.body.Rect;
      reader.readMessage(value,proto.tv.yunxi.protobuf.body.Rect.deserializeBinaryFromReader);
      msg.setRect(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tv.yunxi.protobuf.CommandBody.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tv.yunxi.protobuf.CommandBody} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tv.yunxi.protobuf.CommandBody.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExposureParams();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.tv.yunxi.protobuf.body.ManualExposureParams.serializeBinaryToWriter
    );
  }
  f = message.getWhiteBalanceManual();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.tv.yunxi.protobuf.body.WhiteBalanceManual.serializeBinaryToWriter
    );
  }
  f = message.getTransportFile();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.tv.yunxi.protobuf.body.TransportFile.serializeBinaryToWriter
    );
  }
  f = message.getSize();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.tv.yunxi.protobuf.body.Size.serializeBinaryToWriter
    );
  }
  f = message.getRange();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.tv.yunxi.protobuf.body.Range.serializeBinaryToWriter
    );
  }
  f = message.getRect();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.tv.yunxi.protobuf.body.Rect.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 int_val = 1;
 * @return {number}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getIntVal = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.setIntVal = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.clearIntVal = function() {
  return jspb.Message.setOneofField(this, 1, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.hasIntVal = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string str_val = 2;
 * @return {string}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getStrVal = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.setStrVal = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.clearStrVal = function() {
  return jspb.Message.setOneofField(this, 2, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.hasStrVal = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional body.ManualExposureParams exposure_params = 3;
 * @return {?proto.tv.yunxi.protobuf.body.ManualExposureParams}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getExposureParams = function() {
  return /** @type{?proto.tv.yunxi.protobuf.body.ManualExposureParams} */ (
    jspb.Message.getWrapperField(this, proto.tv.yunxi.protobuf.body.ManualExposureParams, 3));
};


/**
 * @param {?proto.tv.yunxi.protobuf.body.ManualExposureParams|undefined} value
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
*/
proto.tv.yunxi.protobuf.CommandBody.prototype.setExposureParams = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.clearExposureParams = function() {
  return this.setExposureParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.hasExposureParams = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional body.WhiteBalanceManual white_balance_manual = 4;
 * @return {?proto.tv.yunxi.protobuf.body.WhiteBalanceManual}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getWhiteBalanceManual = function() {
  return /** @type{?proto.tv.yunxi.protobuf.body.WhiteBalanceManual} */ (
    jspb.Message.getWrapperField(this, proto.tv.yunxi.protobuf.body.WhiteBalanceManual, 4));
};


/**
 * @param {?proto.tv.yunxi.protobuf.body.WhiteBalanceManual|undefined} value
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
*/
proto.tv.yunxi.protobuf.CommandBody.prototype.setWhiteBalanceManual = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.clearWhiteBalanceManual = function() {
  return this.setWhiteBalanceManual(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.hasWhiteBalanceManual = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional body.TransportFile transport_File = 5;
 * @return {?proto.tv.yunxi.protobuf.body.TransportFile}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getTransportFile = function() {
  return /** @type{?proto.tv.yunxi.protobuf.body.TransportFile} */ (
    jspb.Message.getWrapperField(this, proto.tv.yunxi.protobuf.body.TransportFile, 5));
};


/**
 * @param {?proto.tv.yunxi.protobuf.body.TransportFile|undefined} value
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
*/
proto.tv.yunxi.protobuf.CommandBody.prototype.setTransportFile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.clearTransportFile = function() {
  return this.setTransportFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.hasTransportFile = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional body.Size size = 6;
 * @return {?proto.tv.yunxi.protobuf.body.Size}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getSize = function() {
  return /** @type{?proto.tv.yunxi.protobuf.body.Size} */ (
    jspb.Message.getWrapperField(this, proto.tv.yunxi.protobuf.body.Size, 6));
};


/**
 * @param {?proto.tv.yunxi.protobuf.body.Size|undefined} value
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
*/
proto.tv.yunxi.protobuf.CommandBody.prototype.setSize = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.clearSize = function() {
  return this.setSize(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.hasSize = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional body.Range range = 7;
 * @return {?proto.tv.yunxi.protobuf.body.Range}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getRange = function() {
  return /** @type{?proto.tv.yunxi.protobuf.body.Range} */ (
    jspb.Message.getWrapperField(this, proto.tv.yunxi.protobuf.body.Range, 7));
};


/**
 * @param {?proto.tv.yunxi.protobuf.body.Range|undefined} value
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
*/
proto.tv.yunxi.protobuf.CommandBody.prototype.setRange = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.clearRange = function() {
  return this.setRange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.hasRange = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional body.Rect rect = 8;
 * @return {?proto.tv.yunxi.protobuf.body.Rect}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.getRect = function() {
  return /** @type{?proto.tv.yunxi.protobuf.body.Rect} */ (
    jspb.Message.getWrapperField(this, proto.tv.yunxi.protobuf.body.Rect, 8));
};


/**
 * @param {?proto.tv.yunxi.protobuf.body.Rect|undefined} value
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
*/
proto.tv.yunxi.protobuf.CommandBody.prototype.setRect = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.tv.yunxi.protobuf.CommandBody.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.CommandBody} returns this
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.clearRect = function() {
  return this.setRect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.CommandBody.prototype.hasRect = function() {
  return jspb.Message.getField(this, 8) != null;
};


