// source: message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.tv.yunxi.protobuf.Message');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.tv.yunxi.protobuf.CommandBody');

goog.forwardDeclare('proto.tv.yunxi.protobuf.CommandId');
goog.forwardDeclare('proto.tv.yunxi.protobuf.MessageType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tv.yunxi.protobuf.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tv.yunxi.protobuf.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tv.yunxi.protobuf.Message.displayName = 'proto.tv.yunxi.protobuf.Message';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tv.yunxi.protobuf.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.tv.yunxi.protobuf.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tv.yunxi.protobuf.Message} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tv.yunxi.protobuf.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    seq: jspb.Message.getFieldWithDefault(msg, 2, 0),
    timeout: jspb.Message.getFieldWithDefault(msg, 3, 0),
    respCode: jspb.Message.getFieldWithDefault(msg, 4, 0),
    id: jspb.Message.getFieldWithDefault(msg, 5, 0),
    body: (f = msg.getBody()) && proto.tv.yunxi.protobuf.CommandBody.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tv.yunxi.protobuf.Message}
 */
proto.tv.yunxi.protobuf.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tv.yunxi.protobuf.Message;
  return proto.tv.yunxi.protobuf.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tv.yunxi.protobuf.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tv.yunxi.protobuf.Message}
 */
proto.tv.yunxi.protobuf.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.tv.yunxi.protobuf.MessageType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSeq(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTimeout(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRespCode(value);
      break;
    case 5:
      var value = /** @type {!proto.tv.yunxi.protobuf.CommandId} */ (reader.readEnum());
      msg.setId(value);
      break;
    case 6:
      var value = new proto.tv.yunxi.protobuf.CommandBody;
      reader.readMessage(value,proto.tv.yunxi.protobuf.CommandBody.deserializeBinaryFromReader);
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tv.yunxi.protobuf.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tv.yunxi.protobuf.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tv.yunxi.protobuf.Message} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tv.yunxi.protobuf.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getSeq();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getTimeout();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getRespCode();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getId();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getBody();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.tv.yunxi.protobuf.CommandBody.serializeBinaryToWriter
    );
  }
};


/**
 * optional MessageType type = 1;
 * @return {!proto.tv.yunxi.protobuf.MessageType}
 */
proto.tv.yunxi.protobuf.Message.prototype.getType = function() {
  return /** @type {!proto.tv.yunxi.protobuf.MessageType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.tv.yunxi.protobuf.MessageType} value
 * @return {!proto.tv.yunxi.protobuf.Message} returns this
 */
proto.tv.yunxi.protobuf.Message.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint32 seq = 2;
 * @return {number}
 */
proto.tv.yunxi.protobuf.Message.prototype.getSeq = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tv.yunxi.protobuf.Message} returns this
 */
proto.tv.yunxi.protobuf.Message.prototype.setSeq = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 timeout = 3;
 * @return {number}
 */
proto.tv.yunxi.protobuf.Message.prototype.getTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.tv.yunxi.protobuf.Message} returns this
 */
proto.tv.yunxi.protobuf.Message.prototype.setTimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 resp_code = 4;
 * @return {number}
 */
proto.tv.yunxi.protobuf.Message.prototype.getRespCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.tv.yunxi.protobuf.Message} returns this
 */
proto.tv.yunxi.protobuf.Message.prototype.setRespCode = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional CommandId id = 5;
 * @return {!proto.tv.yunxi.protobuf.CommandId}
 */
proto.tv.yunxi.protobuf.Message.prototype.getId = function() {
  return /** @type {!proto.tv.yunxi.protobuf.CommandId} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.tv.yunxi.protobuf.CommandId} value
 * @return {!proto.tv.yunxi.protobuf.Message} returns this
 */
proto.tv.yunxi.protobuf.Message.prototype.setId = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional CommandBody body = 6;
 * @return {?proto.tv.yunxi.protobuf.CommandBody}
 */
proto.tv.yunxi.protobuf.Message.prototype.getBody = function() {
  return /** @type{?proto.tv.yunxi.protobuf.CommandBody} */ (
    jspb.Message.getWrapperField(this, proto.tv.yunxi.protobuf.CommandBody, 6));
};


/**
 * @param {?proto.tv.yunxi.protobuf.CommandBody|undefined} value
 * @return {!proto.tv.yunxi.protobuf.Message} returns this
*/
proto.tv.yunxi.protobuf.Message.prototype.setBody = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tv.yunxi.protobuf.Message} returns this
 */
proto.tv.yunxi.protobuf.Message.prototype.clearBody = function() {
  return this.setBody(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tv.yunxi.protobuf.Message.prototype.hasBody = function() {
  return jspb.Message.getField(this, 6) != null;
};


