// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "command_id_enum.proto" (package "tv.yunxi.protobuf", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tv.yunxi.protobuf.CommandId
 */
export enum CommandId {
    /**
     * @generated from protobuf enum value: CID_NONE = 0;
     */
    CID_NONE = 0,
    /**
     * @generated from protobuf enum value: CID_UPDATE_ROM = 1;
     */
    CID_UPDATE_ROM = 1,
    /**
     * @generated from protobuf enum value: CID_CURRENT_ROM_VERSION = 2;
     */
    CID_CURRENT_ROM_VERSION = 2,
    /**
     * @generated from protobuf enum value: CID_TRANSFORM_FILE = 3;
     */
    CID_TRANSFORM_FILE = 3,
    /**
     * @generated from protobuf enum value: CID_SCENE = 4;
     */
    CID_SCENE = 4,
    /**
     * @generated from protobuf enum value: CID_FRAME_RATE = 5;
     */
    CID_FRAME_RATE = 5,
    /**
     * @generated from protobuf enum value: CID_RESOLUTION = 6;
     */
    CID_RESOLUTION = 6,
    /**
     * @generated from protobuf enum value: CID_BRIGHTNESS = 7;
     */
    CID_BRIGHTNESS = 7,
    /**
     * @generated from protobuf enum value: CID_SHARPNESS = 8;
     */
    CID_SHARPNESS = 8,
    /**
     * @generated from protobuf enum value: CID_CONTRAST = 9;
     */
    CID_CONTRAST = 9,
    /**
     * @generated from protobuf enum value: CID_SATURATION = 10;
     */
    CID_SATURATION = 10,
    /**
     * @generated from protobuf enum value: CID_HUE = 11;
     */
    CID_HUE = 11,
    /**
     * @generated from protobuf enum value: CID_GAMMA = 12;
     */
    CID_GAMMA = 12,
    /**
     * @generated from protobuf enum value: CID_ZOOM = 13;
     */
    CID_ZOOM = 13,
    /**
     * @generated from protobuf enum value: CID_EXPOSURE_MODE = 14;
     */
    CID_EXPOSURE_MODE = 14,
    /**
     * @generated from protobuf enum value: CID_EXPOSURE_EV = 15;
     */
    CID_EXPOSURE_EV = 15,
    /**
     * @generated from protobuf enum value: CID_ANTI_FLICKER = 16;
     */
    CID_ANTI_FLICKER = 16,
    /**
     * @generated from protobuf enum value: CID_EXPOSURE_ISO = 17;
     */
    CID_EXPOSURE_ISO = 17,
    /**
     * @generated from protobuf enum value: CID_EXPOSURE_TIME = 18;
     */
    CID_EXPOSURE_TIME = 18,
    /**
     * @generated from protobuf enum value: CID_EXPOSURE_ABSOLUTE_TIME = 19;
     */
    CID_EXPOSURE_ABSOLUTE_TIME = 19,
    /**
     * @generated from protobuf enum value: CID_EXPOSURE_APERTURE = 20;
     */
    CID_EXPOSURE_APERTURE = 20,
    /**
     * @generated from protobuf enum value: CID_WHITE_BALANCE_MODE = 21;
     */
    CID_WHITE_BALANCE_MODE = 21,
    /**
     * @generated from protobuf enum value: CID_WHITE_BALANCE_TEMPERATURE = 22;
     */
    CID_WHITE_BALANCE_TEMPERATURE = 22,
    /**
     * @generated from protobuf enum value: CID_FOCUS_MODE = 23;
     */
    CID_FOCUS_MODE = 23,
    /**
     * @generated from protobuf enum value: CID_FOCUS_TARGET_LOCATION = 24;
     */
    CID_FOCUS_TARGET_LOCATION = 24,
    /**
     * @generated from protobuf enum value: CID_FOCUS_TARGET_DISTANCE = 25;
     */
    CID_FOCUS_TARGET_DISTANCE = 25
}
