// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "message_type_enum.proto" (package "tv.yunxi.protobuf", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum tv.yunxi.protobuf.MessageType
 */
export enum MessageType {
    /**
     * @generated from protobuf enum value: TYPE_NONE = 0;
     */
    TYPE_NONE = 0,
    /**
     * @generated from protobuf enum value: TYPE_REQUEST = 1;
     */
    TYPE_REQUEST = 1,
    /**
     * @generated from protobuf enum value: TYPE_SET = 2;
     */
    TYPE_SET = 2,
    /**
     * @generated from protobuf enum value: TYPE_POST = 3;
     */
    TYPE_POST = 3,
    /**
     * @generated from protobuf enum value: TYPE_RESPONSE = 4;
     */
    TYPE_RESPONSE = 4
}
